#
# Makefile for misc devices that really don't fit anywhere else.
#

ifeq ($(CONFIG_MTK_CAM_PD2204F_EX), y)
obj-y += ois_dw9781c.o
endif
ifeq ($(CONFIG_MTK_CAM_PD2215F_EX), y)
obj-y += ois_dw9781c.o
endif
ifeq ($(CONFIG_MTK_CAM_PD2257F_EX), y)
obj-y += ois_dw9781c.o
endif
